"""
=====================================================
BioForge Report Generator
Author  : Suryansh Singh Yadav
Version : 2.0
=====================================================
"""

import os
from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.enums import TA_CENTER


def generate_report(header, sequence, length, counts, gc, at):
    """
    Generate BioForge PDF Report
    """

    # -----------------------------
    # Create reports folder
    # -----------------------------
    os.makedirs("reports", exist_ok=True)

    # -----------------------------
    # File Name
    # -----------------------------
    current_time = datetime.now().strftime("%Y%m%d_%H%M%S")

    filename = f"reports/BioForge_Report_{current_time}.pdf"

    # -----------------------------
    # PDF
    # -----------------------------
    pdf = SimpleDocTemplate(filename)

    styles = getSampleStyleSheet()

    title = styles["Title"]
    title.alignment = TA_CENTER

    story = []

    # -----------------------------
    # Title
    # -----------------------------
    story.append(Paragraph("🧬 BioForge DNA Analysis Report", title))
    story.append(Spacer(1, 20))

    # -----------------------------
    # General Information
    # -----------------------------
    story.append(Paragraph("<b>Sequence Information</b>", styles["Heading2"]))

    story.append(Paragraph(f"<b>Sequence Name :</b> {header}", styles["BodyText"]))

    story.append(Paragraph(f"<b>Sequence Length :</b> {length}", styles["BodyText"]))

    story.append(
        Paragraph(
            f"<b>Date :</b> {datetime.now().strftime('%d-%m-%Y %H:%M:%S')}",
            styles["BodyText"]
        )
    )

    story.append(Spacer(1, 20))

    # -----------------------------
    # Base Count Table
    # -----------------------------
    story.append(Paragraph("<b>Base Count</b>", styles["Heading2"]))

    data = [
        ["Base", "Count"],
        ["A", counts["A"]],
        ["T", counts["T"]],
        ["G", counts["G"]],
        ["C", counts["C"]]
    ]

    table = Table(data)

    table.setStyle(

        TableStyle([

            ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

            ("GRID", (0, 0), (-1, -1), 1, colors.black),

            ("ALIGN", (0, 0), (-1, -1), "CENTER"),

            ("BOTTOMPADDING", (0, 0), (-1, 0), 10),

            ("BACKGROUND", (0, 1), (-1, -1), colors.beige)

        ])

    )

    story.append(table)

    story.append(Spacer(1, 20))

    # -----------------------------
    # GC / AT
    # -----------------------------
    story.append(Paragraph("<b>Composition</b>", styles["Heading2"]))

    story.append(
        Paragraph(f"<b>GC Content :</b> {gc:.2f} %", styles["BodyText"])
    )

    story.append(
        Paragraph(f"<b>AT Content :</b> {at:.2f} %", styles["BodyText"])
    )

    story.append(Spacer(1, 20))

    # -----------------------------
    # Sequence
    # -----------------------------
    story.append(Paragraph("<b>DNA Sequence</b>", styles["Heading2"]))

    story.append(
        Paragraph(sequence, styles["Code"])
    )

    story.append(Spacer(1, 20))

    # -----------------------------
    # Footer
    # -----------------------------
    story.append(
        Paragraph(
            "<b>Generated by BioForge v2.0</b>",
            styles["Heading3"]
        )
    )

    story.append(
        Paragraph(
            "Author : Aman Yadav",
            styles["BodyText"]
        )
    )

    # -----------------------------
    # Build PDF
    # -----------------------------
    pdf.build(story)

    print("\n✅ PDF Generated Successfully!")

    print(f"Saved To : {filename}")